DefineUnitType("unit-hero-alan-schezar-turret", {Name = "Alan Turret"
, Image = image_235_terran_goliatht
, Shadow = {"offset", {-7, -7}, "scale", 1}
, Icon = "icon-terran-command-center"
, Animations = "animations-dummy-still"
, Portrait = portrait_tgoliath
, HitPoints = 256
, TileSize = {1, 1}
, BoxSize = {2, 2}
, SightRange = 32
, ComputerReactionRange = math.ceil(32 * ComputerReactionRangeFactor)
, PersonReactionRange = math.floor(32 * PersonReactionRangeFactor)
, NumDirections = image_235_terran_goliatht_NumDirections
, AirUnit = false
, Type = "land"
, Building = false
, organic = false
, LandUnit = true
, Costs = {"time", 0, "minerals", 1, "gas", 1}
, Sounds = {}
})
